storage: ../cache

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    cache: true

packages:
  '@*/*':
    access: $all
    publish: $all
    proxy: npmjs
  '**':
    access: $all
    publish: $all
    proxy: npmjs
log: { type: stdout, format: pretty, level: http }
